### PR TITLE
Added bridge reference for HordeAutoWebBridge current capabilities.

### PR DESCRIPTION
**Pull request by LostRuins**
Karras support has exceptions: a1111 does not have karras for the samplers dpm_fast, euler_a, euler and heun. 
Other samplers should work with karras. Let me know if that means it should be removed.

Tiling support is added but won't be triggered as worker is still on bridge version 7 now, until I manage to get R2 uploading to work correctly.

### CODE REVIEW

**Comment by db0** [comment]
Hmm, I'll need to figure out a way to signify which samplers are supported by each version and then also signify if karras is supported for each of them :-/ For now I suggest you silently drop karras on those samplers to avoid crashing

**Comment by LostRuins** [comment]
Yeap, already done. It fails gracefully, if karras is not found, it goes for the regular version of the sampler.

**Comment by db0** [comment]
Can you rebase this on main and also add sampler capabilities?

**Comment by LostRuins** [comment]
Alright, updated the sampler capabilities, hope I did it correctly. 

Also, not sure if I'm doing something wrong but github won't allow me to update with rebase here, only a regular merge update. see the screenshot, [probably a repo setting](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-rebasing-for-pull-requests). So if you need it rebased might have to do it on your end. Anyway I think this should be okay.

image

**Comment by db0** [comment]
It's probably because you used your main branch for the PR instead of a branch

**Pull request merged**
