### PR TITLE
Fix for some minor bugs/oversights

### PR DESCRIPTION
**Pull request by tazlin**
Fixed a couple of cases of {e} not referring to a variable, cases of missing `self.`, `check_key` missing self parameter, a missing import, and a duplicated dictionary entry.

### CODE REVIEW

**Comment by tazlin** [comment]
FYI this is a request against dbo:kaimerge

**Comment by db0** [comment]
Why did you close?

**Comment by tazlin** [comment]
It was consistently needing to be rebased (hence the force pushes). You had made several commits and there was nothing urgent. I didn’t want you to get to it and see conflicts and be annoyed. I’ll make a bigger PR as I continue to test your PR.

**Comment by db0** [comment]
gotcha

**Pull request closed without merging**
